#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features = 'cxx test',
    source   = ['cpuid_tests.cpp'] + bld.path.ant_glob('src/test_cpuinfo_x86.cpp'),
    target   = 'cpuid_tests',
    use = ['gtest'])
