#! /usr/bin/env python
# encoding: utf-8

bld.stlib \
(
    features        = 'cxx',
    source          = bld.path.ant_glob('**/*.cpp'),
    target          = 'cpuid',
    export_includes = ['..'],
    use             = ['boost_includes', 'boost_thread', 'boost_system']
)
