#! /usr/bin/env python
# encoding: utf-8

from waflib import Context

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='cpuid',
    export_includes=['..'],
    export_defines=[
        'STEINWURF_{}_VERSION="{}"'.format(
            Context.g_module.APPNAME.upper(), Context.g_module.VERSION)],
    use=['platform_includes']
)

# Add a manual dependency to rebuild cpuinfo.cpp if a header file changes.
# waf cannot detect this dependency, because the headers are included
# conditionally based on the platform
bld.add_manual_dependency(
    bld.path.find_node('cpuinfo.cpp'),
    bld.path.ant_glob('**/*.hpp'))
