#! /usr/bin/env python
# encoding: utf-8

bld.stlib \
(
    features        = 'cxx',
    source          = bld.path.ant_glob('**/*.cpp') +
                      bld.path.ant_glob('**/*.hpp'),
    target          = 'cpuid',
    export_includes = ['..'],
    use             = ['boost_includes', 'boost_thread',
                       'boost_chrono', 'boost_timer', 'boost_system']
)
