name: CMake
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
env:
  EXTRA_RESOLVE_OPTIONS: ${{ github.event.inputs.resolve_options }}
jobs:
  # native CMake build
  cmake_build:
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, macOS_X64]
    runs-on: [self-hosted, "${{ matrix.os }}", cmake, builder]
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMake Cleanup
        run: cmake -E remove_directory ${{github.workspace}}/build
      - name: CMake Setup
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: CMake Configure
        env:
          GIT_SSH_COMMAND: "${{ 'ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes' }}"
        working-directory: ${{github.workspace}}/build
        run: cmake ${{github.workspace}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
  # Docker Cmake builds
  docker_builds:
    strategy:
      fail-fast: false
      matrix:
        config:
          - container: ghcr.io/steinwurf/cmake-3.12-gcc:1.0.0
            name: Cmake 3.12.4 (GCC)
          - container: ghcr.io/steinwurf/cmake-3.12-clang:1.0.0
            name: Cmake 3.12.4 (Clang)
    runs-on: [self-hosted, docker, builder]
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMake Cleanup
        run: cmake -E remove_directory build
      - name: CMake Setup
        run: cmake -E make_directory build
      - name: CMake Configure
        working-directory: ${{github.workspace}}/build
        run: cmake ../ -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS"
      - name: CMake Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
